### ISSUE TITLE
I'm reading the code, but I'm curious

### ISSUE THREAD

**Issue by dataf3l** [ortegacmanuel/Kunuku#1]
What does this app do?
Does it do anything at all?

**Comment by ortegacmanuel** [comment]
It's just a starting demo app for the management of delivery activities for agroecological co-ops and groups. I did it just for a talk in order to demonstrate how to start a Rails app using the gem [inline_forms](https://github.com/acesuares/inline_forms)

**Comment by dataf3l** [comment]
Cool, thanks for the explanation :)
